version: '3.0'
services:
    tms-backend:
        container_name: tms-backend
        image: lala
        build:
            context: ./tms-backend
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        command: start
