version: '3.0'
services:
    tms-backend:
        container_name: backend-app
        image: backend-image
        build:
            context: ./tms-backend
            dockerfile: Dockerfile
        ports:
            - 8082:8080
        depends_on:
            - tms-datacenter
        links:
            - tms-datacenter
        command: start
    tms-view:
        container_name: view-app
        image: view-image
        build:
            context: ./tms-view
            dockerfile: DockerFile
        ports:
            - 8080:80
        depends_on:
            - tms-backend
        links:
            - tms-backend
    tms-datacenter:
        container_name: tms-datacenter
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - tms-datacenter:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=tms
            - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
    tms-datacenter: {}