version: '3.0'
services:
    tms-backend:
        container_name: tms-backend
        image: backend
        build:
            context: ./tms-backend
            dockerfile: Dockerfile
        ports:
            - 8082:80
        depends_on:
            - mypostgres
        links:
            - mypostgres
        command: start
    tms-view:
        container_name: tms-view
        image: view
        build:
          context: ./tms-veiew
          dockerfile: DockerFile
        ports:
          - 8080:80
        depends_on:
          - tms-backend
        links:
          - tms-backend
    mypostgres:
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - mypostgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=mydb
            - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
    mypostgres: {}